source 'https://github.com/tpctt/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

target:TimJpushDemo  do

pod 'XAspect'
pod 'JPush','~>3.0.2'

pod 'TimCore/TimCore'


end

